title: Michelle Miller
description: Quick links to my software technical writing publications. https://www.linkedin.com/in/michellemillerprofile/
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
